### ISSUE TITLE
Flock Crashes on Network Connectivity Issues

### ISSUE THREAD

**Issue by mhoak** [jbruestle/flock#1]
In the case that a computer is disconnected from a network for a period of time or goes to sleep while running flock, flock will die when the computer reconnects to the network. Ideally flock should catch the connection error and restart the flock service. Trace below. 

```
Traceback (most recent call last):
  File "/usr/local/bin/flock", line 29, in <module>
    main()
  File "/usr/local/bin/flock", line 27, in main
    the_node.run()
  File "/Library/Python/2.7/site-packages/flock/node.py", line 174, in run
    self.asm.run()
  File "/Library/Python/2.7/site-packages/flock/async.py", line 49, in run
    self.step()
  File "/Library/Python/2.7/site-packages/flock/async.py", line 36, in step
    callback()
  File "/Library/Python/2.7/site-packages/flock/dht.py", line 321, in try_send
    sent = self.buckets[level].try_send()
  File "/Library/Python/2.7/site-packages/flock/dht.py", line 185, in try_send
    lambda err: self.__find_node_failure(node, err))
  File "/Library/Python/2.7/site-packages/flock/dht.py", line 60, in send_request
    raise serr
socket.error: [Errno 51] Network is unreachable
```

**Comment by mhoak** [comment]
This is definitely a low priority issue. Just entered it for tracking.
